name: Deploy
on: [push, workflow_dispatch]
jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: mchangrh/actions/.github/workflows/cf-worker.yml@main
        secrets:
          CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}